### ISSUE TITLE
question about JSON performance

### ISSUE THREAD

**Issue by blacktop** [J-Gras/add-json#2]
Hi @J-Gras can you tell me what this offers over the built-in JSON output logger in Bro?

I was always told that the reason people didn't use the JSON output logger was because it didn't perform well at 'scale' because of how JSON serialization is a slow expensive process?

Have you tested your plugins performance under load?

Thanks!

**Comment by J-Gras** [comment]
Hi @blacktop, the add-json package does not implement its own JSON logger. In fact it's just a wrapper for the built-in ACSII logwriter. In contrast to the `tuning/json-logs.bro` script, it enables JSON logging _in addition_ to the traditional log format. So in the end everything is logged twice. This allows e.g. to ingest JSON logs into an ELK stack for archiving but keep some recent logs in the traditional format on the node itself for debugging.

Regarding performance, spitting out JSON doesn't make much of a difference. But, from my understanding the overall volume increases as fieldnames are contained in every record. Nevertheless, JSON seems to be the first choice for ingesting logs into backends. If you want to scale, writing to disk is usually the bottleneck. Instead you might want to forward logs directly. There are a couple of [discussions](http://mailman.icsi.berkeley.edu/pipermail/bro/2015-January/008093.html) on the Bro mailinglist, elaborating on the different options.

I hope that helps!
Jan
