### ISSUE TITLE
Missing http_ethN-json.log on Security Onion

### ISSUE THREAD

**Issue by louieamone** [J-Gras/add-json#3]
Hi, thanks for making this package available; it helped me get some new data feeds up and running quickly!

Not sure if I'm missing something basic here, but using Security Onion 14.04 and Bro 2.5.5 with the default package install, it looks like I'm getting *-json.log files for all log types except http (which is being written as http_eth4.log in my case).   Is this expected? And if so, do you have a recommended workaround?

Thanks again!

**Comment by J-Gras** [comment]
Hi, that behaviour is somehow expected as the script adds the filter that generates the JSON log only for existing default filters. Security Onion deploys custom filters and hence there is no additional log generated. I will look into supporting filters other thane only the default ones. Thanks a lot for your feedback!

**Comment by J-Gras** [comment]
Turns out I have already added that functionality some time ago. Feel free to test current master.

**Comment by louieamone** [comment]
Sorry for the long pause; I updated add-json.bro from the repo and re-deployed, but seeing the same behavior.  Any recommendations on where to look or how to add logging to see what might be going wrong in my case?  Thanks again.

**Comment by J-Gras** [comment]
I wasn't very precise, sorry! You will have to install the current master using something like ``bro-pkg install add-json --version master`` and redef ``enable_all_filters_json`` to ``T``.
One important note: If the added Security Onion filters make use of ``path_func`` this will most likely not work. At the moment this cannot be fixed but I've noticed that there is some work ongoing in zeek that will allow me to fix the behaviour eventually.
